Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
  SubnetCidr:
    Type: String
    Default: 10.0.0.0/24
    Description: CIDR for the subnet in the VPC
  AppName:
    Type: String
    Default: ""
    Description: Value for the Name tag for all resources in this VPC
  DisconnectedFromInternet:
    Type: String
    Default: ""
Conditions:
  InternetConnected: !Equals
    - !Ref DisconnectedFromInternet
    - ""
Outputs:
  VpcId:
    Description: ID of the created VPC
    Value: !Ref Vpc
  SubnetId:
    Description: Subnet ID
    Value: !Ref Subnet
  RouteTableId:
    Description: Route table for the subnet
    Value: !Ref RouteTable
Resources:
  Vpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      CidrBlock: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: !Ref AppName

  Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !Ref SubnetCidr
      Tags:
        - Key: Name
          Value: !Ref AppName
    DependsOn:
      - RouteTable

  RouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Ref AppName

  RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable

  DefaultGwRoute:
    Type: 'AWS::EC2::Route'
    Conditions: InternetConnected
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref RouteTable
      GatewayId: !Ref Igw

  Igw:
    Type: 'AWS::EC2::InternetGateway'
    Conditions: InternetConnected
    Properties:
      Tags:
        - Key: Name
          Value: !Ref AppName

  IgwAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Conditions: InternetConnected
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref Igw
